package demoproject.springbootdemo.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import demoproject.springbootdemo.models.User;
import demoproject.springbootdemo.repositories.UserRepository;
import demoproject.springbootdemo.services.UserDetailsServiceCustom;

@Controller
public class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserDetailsServiceCustom userDetailsService;

    @PostMapping(path = "/login")
    public String login(@RequestParam String email, @RequestParam String password) {
        User user = userRepository.findByEmail(email);
        if (user == null || !user.getPassword().equals(password))
            return "login";

        System.out.println(user.getName());

        UserDetails userDetails = userDetailsService.loadUserByUsername(email);

        UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken(
                userDetails, null, userDetails.getAuthorities());

        SecurityContextHolder.getContext().setAuthentication(authentication);

        // HttpHeaders responseHeaders = new HttpHeaders();
        // responseHeaders.set("token", authService.generateToken(user));

        return "homePage";
    }

    @GetMapping(path = "/login")
    public String login() {
        return "login";
    }

}